apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu  # select specific node by its hostname
      containers:
      - name: flask-app
        image: flask-llm-app:latest  # local image name
        imagePullPolicy: IfNotPresent  # ensures it uses local image if available
        ports:
        - containerPort: 5000
        env:
        - name: LLM_MODEL_DIR
          value: /models
        volumeMounts:
        - name: models-volume
          mountPath: /models
      volumes:
      - name: models-volume
        hostPath:
          path: /mnt
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500

