apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.2-192.168.2.2
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - my-pool

