---
- name: Install fuse-overlayfs on all clients
  hosts: all
  become: true
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install fuse-overlayfs package (Debian/Ubuntu)
      apt:
        name: fuse-overlayfs
        state: present
      when: ansible_facts['os_family'] == "Debian"
