---
- name: Reinstall K3s on target node
  hosts: k3s_agents
  become: yes
  vars:
    k3s_url: "https://192.168.2.2:6443"
    k3s_token: "K103aa31d0a0b368918aba8ac75d98e3053bfb6c87687f812d7ff0eed7bcc2e979c::server:c787e06d98cc5304c0f0e882930b948a"
  
  tasks:
    - name: Download K3s installer
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install_k3s.sh
        mode: '0755'

    - name: Run K3s agent installer
      shell: |
        set -euxo pipefail
        export K3S_NODE_NAME={{ inventory_hostname }}
        export K3S_URL={{ k3s_url }}
        export K3S_TOKEN={{ k3s_token }}
        export INSTALL_K3S_EXEC="--snapshotter=fuse-overlayfs --kubelet-arg=runtime-request-timeout=5m --kubelet-arg=node-status-update-frequency=10s"
        export INSTALL_K3S_SKIP_SSL_VERIFY=true
        /tmp/install_k3s.sh
      args:
        executable: /bin/bash
